-- 1. Tabel petugas
create table if not exists public.officers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  role text not null default 'officer' check (role in ('superadmin', 'officer', 'masjid')),
  pin_hash text not null default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabel jadwal harian
create table if not exists public.schedule_assignments (
  id bigint generated by default as identity primary key,
  date date not null,
  prayer_id text not null check (prayer_id in ('subuh','dzuhur','ashar','maghrib','isya')),
  imam_id bigint references public.officers(id) on delete set null,
  muadzin_id bigint references public.officers(id) on delete set null,
  badal_imam_id bigint references public.officers(id) on delete set null,
  unique(date, prayer_id)
);

-- 3. Tabel absensi
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  officer_name text not null,
  role text not null check (role in ('Imam','Muadzin','Badal Imam')),
  prayer text not null,
  prayer_time text not null,
  status text not null check (status in ('HADIR','TERLAMBAT','ALFA')),
  scan_time text not null,
  attendance_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3.5. Tabel QR token untuk absensi via scan
create table if not exists public.qr_tokens (
  id bigint generated by default as identity primary key,
  token text unique not null,
  officer_name text not null,
  role text not null check (role in ('Imam','Muadzin','Badal Imam')),
  prayer text not null,
  prayer_time text not null,
  attendance_date date not null,
  used boolean not null default false,
  used_at timestamp with time zone,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Index untuk performa
drop index if exists idx_schedule_assignments_date_prayer;
drop index if exists idx_attendance_date_officer;
drop index if exists idx_qr_tokens_token;

create index idx_schedule_assignments_date_prayer on public.schedule_assignments(date, prayer_id);
-- create index idx_attendance_date_officer on public.attendance(attendance_date, officer_id);
create index idx_qr_tokens_token on public.qr_tokens(token);

-- 5. RLS
alter table public.officers enable row level security;
alter table public.schedule_assignments enable row level security;
alter table public.attendance enable row level security;
alter table public.qr_tokens enable row level security;

-- 6. Hapus policy lama jika ada, lalu buat policy baru untuk officers
drop policy if exists "Public read officers" on public.officers;
drop policy if exists "Public insert officers" on public.officers;
drop policy if exists "Public update officers" on public.officers;
drop policy if exists "Public delete officers" on public.officers;

create policy "Public read officers" on public.officers for select using (true);
create policy "Public insert officers" on public.officers for insert with check (true);
create policy "Public update officers" on public.officers for update using (true);
create policy "Public delete officers" on public.officers for delete using (true);

-- 7. Hapus policy lama jika ada, lalu buat policy baru untuk schedule_assignments
drop policy if exists "Public read schedule_assignments" on public.schedule_assignments;
drop policy if exists "Public insert schedule_assignments" on public.schedule_assignments;
drop policy if exists "Public update schedule_assignments" on public.schedule_assignments;
drop policy if exists "Public delete schedule_assignments" on public.schedule_assignments;

create policy "Public read schedule_assignments" on public.schedule_assignments for select using (true);
create policy "Public insert schedule_assignments" on public.schedule_assignments for insert with check (true);
create policy "Public update schedule_assignments" on public.schedule_assignments for update using (true);
create policy "Public delete schedule_assignments" on public.schedule_assignments for delete using (true);

-- 8. Hapus policy lama jika ada, lalu buat policy baru untuk attendance
drop policy if exists "Public read attendance" on public.attendance;
drop policy if exists "Public insert attendance" on public.attendance;
drop policy if exists "Public update attendance" on public.attendance;
drop policy if exists "Public delete attendance" on public.attendance;

create policy "Public read attendance" on public.attendance for select using (true);
create policy "Public insert attendance" on public.attendance for insert with check (true);
create policy "Public update attendance" on public.attendance for update using (true);
create policy "Public delete attendance" on public.attendance for delete using (true);

-- 9. Hapus policy lama jika ada, lalu buat policy baru untuk qr_tokens
drop policy if exists "Public read qr_tokens" on public.qr_tokens;
drop policy if exists "Public insert qr_tokens" on public.qr_tokens;
drop policy if exists "Public update qr_tokens" on public.qr_tokens;
drop policy if exists "Public delete qr_tokens" on public.qr_tokens;

create policy "Public read qr_tokens" on public.qr_tokens for select using (true);
create policy "Public insert qr_tokens" on public.qr_tokens for insert with check (true);
create policy "Public update qr_tokens" on public.qr_tokens for update using (true);
create policy "Public delete qr_tokens" on public.qr_tokens for delete using (true);
